/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lemon.comps;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;

import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableColumn;

import com.eltima.components.ui.DatePicker;
import com.lemon.comps.base.JAutoComboBox;
import com.lemon.comps.base.MyComboBoxEditor;
import com.lemon.linstener.MyWindowListener;
import com.lemon.print.InvoicePrinter;
import com.lemon.utils.AmountUtil;
import com.lemon.utils.ConfigUtils;
import com.lemon.utils.UT;
import com.lemon.vo.base.Company;
import com.lemon.vo.base.Goods;
import com.lemon.vo.template.InvoiceTemplate;
import com.lemon.vo.template.Item;

/**
 * 发票信息主页面
 *
 * @author plin
 *
 */
@SuppressWarnings("ALL")
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        drawDateLabel = new javax.swing.JLabel();
        drawDateField = new DatePicker(this);
        industryClassLabel = new javax.swing.JLabel();
        industryClassField = new javax.swing.JTextField();
        invoiceCodeLabel = new javax.swing.JLabel();
        invoiceCodeField = new javax.swing.JTextField();
        invoiceNoLabel = new javax.swing.JLabel();
        invoiceNoField = new javax.swing.JTextField();
        buyComInfoLabel = new javax.swing.JLabel();
        buyComNameLabel = new javax.swing.JLabel();
        buyComNameField = new JAutoComboBox();
        buyComTaxNoLabel = new javax.swing.JLabel();
        buyComTaxNoField = new javax.swing.JTextField();
        addBuyComInfoButton = new javax.swing.JButton();
        saleComInfoLabel = new javax.swing.JLabel();
        saleComTaxNoLabel = new javax.swing.JLabel();
        saleComNameLabel = new javax.swing.JLabel();
        saleComNameField = new JAutoComboBox();
        saleComTaxNoField = new javax.swing.JTextField();
        addSaleComButton = new javax.swing.JButton();
        saleComBankNoLabel = new javax.swing.JLabel();
        saleComAddressLabel = new javax.swing.JLabel();
        saleComAddressField = new javax.swing.JTextField();
        saleComBankNoField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalInWordLabel = new javax.swing.JLabel();
        totalInWordField = new javax.swing.JTextField();
        totalAmountLabel = new javax.swing.JLabel();
        totalAmountField = new javax.swing.JTextField();
        commentLabel = new javax.swing.JLabel();
        commentField = new javax.swing.JTextField();
        payeeLabel = new javax.swing.JLabel();
        payeeField = new javax.swing.JTextField();
        drawerLabel = new javax.swing.JLabel();
        drawerField = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        refreshButton = new javax.swing.JButton();
        printViewButton = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        exitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        // jMenu1 = new javax.swing.JMenu();
        // backupMenuBar = new javax.swing.JMenuItem();
        // restoreMenuBar = new javax.swing.JMenuItem();
        // jMenu2 = new javax.swing.JMenu();
        // historyInvoiceMenuBar = new javax.swing.JMenuItem();
        // adjustModelMenuBar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        buyComMenuBar = new javax.swing.JMenuItem();
        saleComMenuBar = new javax.swing.JMenuItem();
        goodsInfoMenuBar = new javax.swing.JMenuItem();

        jPrintViewToolBar = new javax.swing.JToolBar();
        printButton = new javax.swing.JButton();

        // drawDateField.setLocale(Locale.CHINESE);// 设置显示语言
        drawDateField.setPattern("yyyy年MM月dd日");// 设置日期格式化字符串
        drawDateField.setDate(new Date());
        drawDateField.setEditorable(false);// 设置是否可编辑
        drawDateField.setBackground(Color.gray);// 设置背景色
        drawDateField.setForeground(Color.yellow);// 设置前景色
        drawDateField.setPreferredSize(new Dimension(124, 32));

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("发票打印软件1.0.0");
        setSize(new java.awt.Dimension(940, 420));
        setResizable(false);
        // 设置关闭监听
        addWindowListener(new MyWindowListener());

        jPanel1.setName("hyfl"); // NOI18N

        drawDateLabel.setText("开票时间：");

        industryClassLabel.setText("行业分类：");

        industryClassField.setText("其他行业");
        industryClassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        invoiceCodeLabel.setText("机打发票代码：");

        invoiceCodeField.setText("");
        invoiceCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        invoiceNoLabel.setText("机打发票号码：");

        invoiceNoField.setText("");
        invoiceNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        buyComInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buyComInfoLabel.setText("<html>购<br>方<br>单<br>位");
        buyComInfoLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));

        buyComNameLabel.setText("购方单位名称：");

        // 设置内容
        buyComNameField.setItems(ConfigUtils.getCompanyItems(ConfigUtils.buyCompanies));
        buyComNameField.addItemListener(new ItemListener() {
            JTextField editor = (JTextField) buyComNameField.getEditor().getEditorComponent();

            public void itemStateChanged(ItemEvent event) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    int caretPosition = editor.getCaretPosition();
                    if (caretPosition != -1) {
                        try {
                            editor.moveCaretPosition(caretPosition);
                        } catch (IllegalArgumentException ex) {
                            ex.printStackTrace();
                        }
                    }
                    changeBuyInfo(editor.getText());
                }
            }
        });

        buyComTaxNoLabel.setText("购方税号：");

        buyComTaxNoField.setText("");
        buyComTaxNoField.setToolTipText("");

        // addBuyComInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N
        addBuyComInfoButton.setText("单位入库");
        addBuyComInfoButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String buyComName = buyComNameField.getText();
                // 修改
                Company com = new Company();
                int index = 0;
                if (buyComName.indexOf(":") != -1) {
                    index = Integer.parseInt(buyComName.split(":")[0]);
                    com.setId(index);
                    com.setName(buyComName.split(":")[1]);
                    com.setTaxpayerID(buyComTaxNoField.getText());
                    com.setAddrAndPhone("");
                    com.setBankNameAndNo("");
                } else {
                    // 新增
                    index = ConfigUtils.getIndex(ConfigUtils.INDEX_NAME[1]);
                    // 重新加载数据
                    com.setId(index);
                    com.setName(buyComName);
                    com.setTaxpayerID(buyComTaxNoField.getText());
                    com.setAddrAndPhone("");
                    com.setBankNameAndNo("");
                }
                ConfigUtils.buyCompanies.put(index, com);
                if (buyComView != null) {
                    buyComView.reInitData();
                }
            }
        });

        saleComInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saleComInfoLabel.setText("<html>销<br>方<br>单<br>位");
        saleComInfoLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        saleComTaxNoLabel.setText("销方税号：");

        saleComNameLabel.setText("销方单位名称：");

        saleComNameField.setItems(ConfigUtils.getCompanyItems(ConfigUtils.saleCompanies));
        saleComNameField.addItemListener(new ItemListener() {
            JTextField editor = (JTextField) saleComNameField.getEditor().getEditorComponent();

            public void itemStateChanged(ItemEvent event) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    int caretPosition = editor.getCaretPosition();
                    if (caretPosition != -1) {
                        try {
                            editor.moveCaretPosition(caretPosition);
                        } catch (IllegalArgumentException ex) {
                            ex.printStackTrace();
                        }
                    }
                    changeSaleInfo(editor.getText());
                }
            }
        });

        saleComTaxNoField.setText("");
        saleComTaxNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        // addSaleComButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/test/plus.png"))); // NOI18N
        addSaleComButton.setText("单位入库");
        addSaleComButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Company com = new Company();
                String saleComName = saleComNameField.getText();

                // 修改
                int index = 0;
                if (saleComName.indexOf(":") != -1) {
                    index = Integer.parseInt(saleComName.split(":")[0]);
                    com.setId(index);
                    com.setName(saleComName.split(":")[1]);
                    com.setTaxpayerID(saleComTaxNoField.getText());
                    com.setAddrAndPhone(saleComAddressField.getText());
                    com.setBankNameAndNo(saleComBankNoField.getText());
                } else {
                    index = ConfigUtils.getIndex(ConfigUtils.INDEX_NAME[0]);
                    // 重新加载数据
                    com.setId(index);
                    com.setName(saleComName);
                    com.setTaxpayerID(saleComTaxNoField.getText());
                    com.setAddrAndPhone(saleComAddressField.getText());
                    com.setBankNameAndNo(saleComBankNoField.getText());
                }
                ConfigUtils.saleCompanies.put(index, com);
                if (saleComView != null) {
                    saleComView.reInitData();
                }
            }
        });

        saleComBankNoLabel.setText("销方银行账号：");

        saleComAddressLabel.setText("销方地址电话：");

        saleComAddressField.setText("");
        saleComAddressField.setToolTipText("");
        saleComAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        saleComBankNoField.setText("");
        saleComBankNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] { { 1, null, null, null, null, null, null }, { 2, null, null, null, null, null, null },
                        { 3, null, null, null, null, null, null }, { 4, null, null, null, null, null, null }, { 5, null, null, null, null, null, null } },
                new String[] { "序号", "商品名称", "规格型号", "单位", "数量", "单价", "金额" }) {
            Class[] types = new Class[] { Integer.class, String.class, String.class, String.class, Integer.class, BigDecimal.class, BigDecimal.class };
            boolean[] canEdit = new boolean[] { false, true, true, true, true, true, true };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(12);
        }
        TableColumn col = jTable1.getColumnModel().getColumn(1);
        col.setCellEditor(new MyComboBoxEditor(ConfigUtils.getGoodsItems()));
        jTable1.getModel().addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                // 数量
                if (e.getColumn() == 4) {
                    calcTotalAmount(jTable1.getSelectedRow());
                }
                // 商品名称下拉框
                if (e.getColumn() == 1) {
                    int row = jTable1.getSelectedRow();
                    int col = 1;
                    if (e.getType() == TableModelEvent.UPDATE) {
                        /*
                         * do some thing 获得编辑后单元格得值
                         */
                        String newvalue = UT.nvl(jTable1.getValueAt(row, 1));
                        changeGoodsInfo(row, newvalue);
                    }
                }
            }
        });

        totalInWordLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        totalInWordLabel.setText("合计大写：");

        totalInWordField.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        // totalInWordField.setText("壹万叁仟陆佰捌拾柒元伍角整");

        totalAmountLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        totalAmountLabel.setText("合计小写：");

        totalAmountField.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        // totalAmountField.setText("（¥）13,687.50");
        totalAmountField.setToolTipText("");

        commentLabel.setText("备注：");

        payeeLabel.setText("收款人：");

        payeeField.setText("");

        drawerLabel.setText("开票人：");

        drawerField.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout
                .setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(jScrollPane1).addContainerGap()).addGroup(jPanel1Layout
                                        .createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(buyComInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(buyComNameLabel).addComponent(buyComTaxNoLabel))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(buyComTaxNoField)
                                                                .addComponent(buyComNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18).addComponent(addBuyComInfoButton))
                                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(drawDateLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(drawDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 124,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(33, 33, 33).addComponent(industryClassLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(industryClassField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33,
                                                33)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup().addComponent(invoiceCodeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(invoiceCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18).addComponent(invoiceNoLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(invoiceNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(28, 28, 28))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(saleComInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(saleComNameLabel).addComponent(saleComTaxNoLabel))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(saleComTaxNoField).addComponent(saleComNameField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                                                                .addGap(18, 18, 18).addComponent(addSaleComButton))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(saleComAddressLabel).addComponent(saleComBankNoLabel))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(saleComBankNoField).addComponent(saleComAddressField))))
                                                                .addContainerGap())))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(totalInWordLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(totalInWordField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(payeeLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(payeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18).addComponent(drawerLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(drawerField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(totalAmountLabel)
                                                .addComponent(commentLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(commentField)
                                                .addComponent(totalAmountField, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))))));
        jPanel1Layout
                .setVerticalGroup(
                        jPanel1Layout
                                .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(drawDateLabel)
                                                .addComponent(drawDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(industryClassLabel)
                                                .addComponent(industryClassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(invoiceCodeLabel)
                                                .addComponent(invoiceCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(
                                                        invoiceNoLabel)
                                                .addComponent(invoiceNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel1Layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout
                                                        .createSequentialGroup().addGroup(jPanel1Layout
                                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(buyComNameLabel).addComponent(buyComNameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(addBuyComInfoButton))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(buyComTaxNoLabel).addComponent(buyComTaxNoField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(saleComNameLabel).addComponent(saleComNameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(addSaleComButton))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(saleComTaxNoLabel).addComponent(saleComTaxNoField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(saleComAddressLabel).addComponent(saleComAddressField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(saleComBankNoLabel).addComponent(saleComBankNoField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(saleComInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                .addComponent(buyComInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(totalInWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(totalInWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(commentField)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(drawerLabel).addComponent(drawerField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(payeeLabel)
                                                        .addComponent(payeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(commentLabel))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jToolBar2.setRollover(true);

        refreshButton.setText("信息刷新");
        refreshButton.setFocusable(false);
        refreshButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // 信息刷新
                refreshInfoAction(e);
            }
        });
        jToolBar2.add(refreshButton);

        printViewButton.setText("打印预览");
        printViewButton.setFocusable(false);
        printViewButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // 打印发票
                printInvoiceAction(e);
            }
        });
        jToolBar2.add(printViewButton);

        jToolBar3.setRollover(true);

        exitButton.setText("退出系统");
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // 退出系统
                systemExitActionPerformed(e);
            }
        });
        jToolBar3.add(exitButton);

        jPrintViewToolBar.setRollover(true);

        printButton.setText("打印发票");
        printButton.setFocusable(false);
        printButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        printButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // 发票打印
                java.util.List<Item> items = printerView.getItems();
                InvoiceTemplate template = new InvoiceTemplate();
                template.setItems(items);
                InvoicePrinter invoicePrinter = new InvoicePrinter(template);
                invoicePrinter.doPrint();
            }
        });
        jPrintViewToolBar.add(printButton);

        // jMenu1.setText("系统设置");
        //
        // backupMenuBar.setText("信息备份");
        // backupMenuBar.addActionListener(new java.awt.event.ActionListener() {
        // public void actionPerformed(java.awt.event.ActionEvent evt) {
        // jMenuItem1ActionPerformed(evt);
        // }
        // });
        // jMenu1.add(backupMenuBar);
        //
        // restoreMenuBar.setText("信息还原");
        // restoreMenuBar.addActionListener(new java.awt.event.ActionListener() {
        // public void actionPerformed(java.awt.event.ActionEvent evt) {
        // jMenuItem3ActionPerformed(evt);
        // }
        // });
        // jMenu1.add(restoreMenuBar);

        // jMenuBar1.add(jMenu1);

        // jMenu2.setText("发票信息");
        //
        // historyInvoiceMenuBar.setText("历史开票");
        // jMenu2.add(historyInvoiceMenuBar);
        //
        // adjustModelMenuBar.setText("模版微调");
        // jMenu2.add(adjustModelMenuBar);
        //
        // jMenuBar1.add(jMenu2);

        jMenu3.setText("信息管理");

        buyComMenuBar.setText("购方信息");
        jMenu3.add(buyComMenuBar);

        buyComMenuBar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                buyComMenuBarActionPerformed(e);
            }
        });

        saleComMenuBar.setText("销方信息");
        jMenu3.add(saleComMenuBar);

        saleComMenuBar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                saleComMenuBarActionPerformed(e);
            }
        });

        goodsInfoMenuBar.setText("商品信息");
        goodsInfoMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodsInfoMenuBarActionPerformed(evt);
            }
        });

        jMenu3.add(goodsInfoMenuBar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));

        pack();

        // 初始化
        changeBuyInfo(buyComNameField.getText());
        // 初始化
        changeSaleInfo(saleComNameField.getText());
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // 系统备份
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField10ActionPerformed

    /**
     * 发票打印
     *
     * @param evt
     */
    private void printInvoiceAction(java.awt.event.ActionEvent evt) {
        // 1.提示信息
        if (ConfigUtils.itemsMap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "模版信息未加载", "警告", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 2.设置数据
        String buyCompanyName = null;
        String saleCompanyName = null;
        String tmp[] = null;
        Map<String, Item> map = ConfigUtils.itemsMap;
        java.util.List<Item> items = new ArrayList<Item>();
        for (String key : map.keySet()) {
            Item item = UT.copy(map.get(key));
            String text = null;
            switch (Integer.parseInt(key)) {
                // 开票日期
                case 1:
                    text = drawDateField.getText();
                    break;
                // 行业分类
                case 2:
                    text = industryClassField.getText();
                    break;
                // 机打发票代码
                case 4:
                    text = invoiceCodeField.getText();
                    break;
                // 机打发票号码
                case 6:
                    text = invoiceNoField.getText();
                    break;
                // 购方单位名称
                case 8:
                    if ((buyCompanyName = buyComNameField.getText()) != null) {
                        tmp = buyCompanyName.split(":");
                        if (tmp.length > 1) {
                            text = tmp[1];
                        } else {
                            text = tmp[0];
                        }
                    }
                    break;
                // 购方税号
                case 10:
                    text = buyComTaxNoField.getText();
                    break;
                // 商品信息，另作处理
                case 17:
                case 18:
                case 19:
                case 20:
                case 21:
                case 22:
                    break;
                // 金额大写
                case 40:
                    text = totalInWordField.getText();
                    break;
                // 金额小写
                case 24:
                    text = "（¥）" + UT.format(totalAmountField.getText());
                    break;
                // 销方单位名称
                case 26:
                    if ((saleCompanyName = saleComNameField.getText()) != null) {
                        tmp = saleCompanyName.split(":");
                        if (tmp.length > 1) {
                            text = tmp[1];
                        } else {
                            text = tmp[0];
                        }
                    }
                    break;
                // 销方税号
                case 28:
                    text = saleComTaxNoField.getText();
                    break;
                // 销方地址电话
                case 30:
                    text = saleComAddressField.getText();
                    break;
                // 销方银行账号
                case 32:
                    text = saleComBankNoField.getText();
                    break;
                // 备注
                case 34:
                    text = commentField.getText();
                    break;
                // 收款人
                case 36:
                    text = payeeField.getText();
                    break;
                // 开票人
                case 38:
                    text = drawerField.getText();
                    break;
                default:
                    ;
            }
            if (text != null) {
                item.setText(text);
            }
            items.add(item);
        }
        // 3.商品信息
        int row = jTable1.getRowCount();
        int col = jTable1.getColumnCount();

        // 序号
        int index = 0;
        // 商品名称
        String goodsName = null;

        // 行
        for (int r = 0; r < row; r++) {
            index = (Integer) jTable1.getValueAt(r, 0);
            goodsName = (String) jTable1.getValueAt(r, 1);
            if (goodsName == null || goodsName.equals("")) {
                continue;
            } else {
                goodsName = goodsName.split(":")[1];
            }
            if (index > 1) {
                items.add(copyItem(goodsName, "17", index, false));
                // 规格型号
                items.add(copyItem(jTable1.getValueAt(r, 2), "18", index, false));
                // 单位
                items.add(copyItem(jTable1.getValueAt(r, 3), "19", index, false));
                // 数量
                items.add(copyItem(jTable1.getValueAt(r, 4), "20", index, false));
                // 单价
                items.add(copyItem(jTable1.getValueAt(r, 5), "21", index, true));
                // 金额
                items.add(copyItem(jTable1.getValueAt(r, 6), "22", index, true));
            } else {
                items.add(copyItem(goodsName, "17", false));
                // 规格型号
                items.add(copyItem(jTable1.getValueAt(r, 2), "18", false));
                // 单位
                items.add(copyItem(jTable1.getValueAt(r, 3), "19", false));
                // 数量
                items.add(copyItem(jTable1.getValueAt(r, 4), "20", false));
                // 单价
                items.add(copyItem(jTable1.getValueAt(r, 5), "21", true));
                // 金额
                items.add(copyItem(jTable1.getValueAt(r, 6), "22", true));
            }
        }
        // 4.预览
        if (printViewDialog == null) {
            printViewDialog = new JDialog(this, "购方单位信息");
            printViewDialog.setLocation(20, 20);
            printViewDialog.setSize(800, 500);
            printViewDialog.setLocationRelativeTo(this);
            printerView = new PrinterView(items);
            // 取得JInternalFrame的Content Pane,用以加入新的组件。
            Container icontentPane = printViewDialog.getContentPane();

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(icontentPane);
            icontentPane.setLayout(layout);
            layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addComponent(jPrintViewToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(printerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
            layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPrintViewToolBar,
                            javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(printerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));

        } else {
            printerView.setItems(items);
            printerView.repaint();
        }
        printViewDialog.setVisible(true);
    }

    private void refreshInfoAction(java.awt.event.ActionEvent evt) {
        // 商品信息
        TableColumn col = jTable1.getColumnModel().getColumn(1);
        col.setCellEditor(new MyComboBoxEditor(ConfigUtils.getGoodsItems()));
        // 购方信息
        buyComNameField.setItems(ConfigUtils.getCompanyItems(ConfigUtils.buyCompanies));
        // 售方信息
        saleComNameField.setItems(ConfigUtils.getCompanyItems(ConfigUtils.saleCompanies));
    }

    /**
     * 复制新元素
     * 
     * @param value
     * @param key
     * @param index
     * @param format
     * @return
     */
    private Item copyItem(Object value, String key, int index, boolean format) {
        Item item = new Item();
        Item source = ConfigUtils.itemsMap.get(key);
        if (format) {
            item.setText(UT.format(value));
        } else {
            item.setText(value.toString());
        }
        item.setAlign(source.getAlign());
        item.setX(source.getX());
        item.setY(source.getY() + 5 * (index - 1));
        item.setId(key + index);
        return item;
    }

    /**
     * 复制新元素
     *
     * @param value
     * @param key
     * @param format
     * @return
     */
    private Item copyItem(Object value, String key, boolean format) {
        Item item = new Item();
        Item source = ConfigUtils.itemsMap.get(key);
        if (format) {
            item.setText(UT.format(value));
        } else {
            item.setText(value.toString());
        }
        item.setAlign(source.getAlign());
        item.setX(source.getX());
        item.setY(source.getY());
        item.setId(key);
        return item;
    }

    private void systemExitActionPerformed(java.awt.event.ActionEvent e) {
        int i = JOptionPane.showConfirmDialog(this, "确定退出？", "提示", JOptionPane.YES_NO_OPTION);
        if (i == 1) {
            return;
        }
        if (i == 0) {
            // 保存数据
            ConfigUtils.save();
            System.exit(0);
        }
    }

    private void buyComMenuBarActionPerformed(ActionEvent e) {
        if (buyComDialog == null) {
            buyComDialog = new JDialog(this, "购方单位信息");
            buyComDialog.setLocation(20, 20);
            buyComDialog.setSize(800, 400);
            buyComDialog.setLocationRelativeTo(this);
            // 取得JInternalFrame的Content Pane,用以加入新的组件。
            Container icontentPane = buyComDialog.getContentPane();
            buyComView = new BuyCompanyView();
            icontentPane.add(buyComView);
        }
        buyComDialog.setVisible(true);
    }

    /**
     * 自动填充买方信息
     * 
     * @param item
     */
    private void changeBuyInfo(String item) {
        Company select = ConfigUtils.getCompanyByItem(item, ConfigUtils.buyCompanies);
        if (select != null) {
            // 设置税号
            buyComTaxNoField.setText(UT.nvl(select.getTaxpayerID()));
        }
    }

    private void saleComMenuBarActionPerformed(ActionEvent e) {
        if (saleComDialog == null) {
            saleComDialog = new JDialog(this, "销方单位信息");
            saleComDialog.setLocation(20, 20);
            saleComDialog.setSize(800, 400);
            saleComDialog.setLocationRelativeTo(this);
            // 取得JInternalFrame的Content Pane,用以加入新的组件。
            Container icontentPane = saleComDialog.getContentPane();
            saleComView = new SaleCompanyView();
            icontentPane.add(saleComView);
        }
        saleComDialog.setVisible(true);
    }

    /**
     * 自动填充卖方信息
     * 
     * @param item
     */
    private void changeSaleInfo(String item) {
        Company select = ConfigUtils.getCompanyByItem(item, ConfigUtils.saleCompanies);
        if (select != null) {
            // 设置税号
            saleComTaxNoField.setText(UT.nvl(select.getTaxpayerID()));
            saleComAddressField.setText(UT.nvl(select.getAddrAndPhone()));
            saleComBankNoField.setText(UT.nvl(select.getBankNameAndNo()));
        }
    }

    private void goodsInfoMenuBarActionPerformed(ActionEvent e) {
        if (goodsInfoDialog == null) {
            goodsInfoDialog = new JDialog(this, "商品信息");
            goodsInfoDialog.setLocation(20, 20);
            goodsInfoDialog.setSize(800, 400);
            goodsInfoDialog.setLocationRelativeTo(this);
            // 取得JInternalFrame的Content Pane,用以加入新的组件。
            Container icontentPane = goodsInfoDialog.getContentPane();
            goodsInfoView = new GoodsInfoView();
            icontentPane.add(goodsInfoView);
        }
        goodsInfoDialog.setVisible(true);
    }

    /**
     * 自动填充商品信息
     *
     * @param row
     * @param newvalue
     */
    private void changeGoodsInfo(int row, String newvalue) {
        if (newvalue.equals("")) {
            // 规格型号
            jTable1.setValueAt("", row, 2);
            // 单位
            jTable1.setValueAt(null, row, 3);
            // 数量
            jTable1.setValueAt(null, row, 4);
            // 单价
            jTable1.setValueAt(null, row, 5);
            // 金额
            jTable1.setValueAt(null, row, 6);
        } else {
            Integer key = Integer.parseInt(newvalue.split(":")[0]);
            Goods goods = ConfigUtils.goodsMap.get(key);
            // 规格型号
            jTable1.setValueAt(goods.getModeType(), row, 2);
            // 单位
            jTable1.setValueAt(goods.getUnit(), row, 3);
            // 单价
            jTable1.setValueAt(goods.getPrice(), row, 5);
        }

        // 计算总金额
        calcTotalAmount(row);
    }

    /**
     * 计算金额和总金额
     * 
     * @param row
     */
    private void calcTotalAmount(int row) {
        // 计算金额
        if (jTable1.getValueAt(row, 4) != null) {
            Integer nums = Integer.parseInt(jTable1.getValueAt(row, 4).toString());
            BigDecimal price = new BigDecimal(jTable1.getValueAt(row, 5).toString());
            jTable1.setValueAt(price.multiply(new BigDecimal(nums)), row, 6);
        }
        // 计算总额度
        BigDecimal total = BigDecimal.ZERO;
        for (int i = 0; i < 5; i++) {
            if (jTable1.getValueAt(i, 6) != null) {
                total = total.add(new BigDecimal(jTable1.getValueAt(i, 6).toString()));
            }
        }
        // 显示总额度
        totalAmountField.setText(total.toString());
        totalInWordField.setText(AmountUtil.getAmountInWords(total));
    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton addBuyComInfoButton;
    private javax.swing.JButton addSaleComButton;
    private javax.swing.JButton printViewButton;
    private javax.swing.JLabel drawDateLabel;
    private javax.swing.JLabel saleComNameLabel;
    private javax.swing.JLabel saleComBankNoLabel;
    private javax.swing.JLabel saleComAddressLabel;
    private javax.swing.JLabel totalInWordLabel;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JLabel payeeLabel;
    private javax.swing.JLabel drawerLabel;
    private javax.swing.JLabel industryClassLabel;
    private javax.swing.JLabel invoiceCodeLabel;
    private javax.swing.JLabel invoiceNoLabel;
    private javax.swing.JLabel buyComInfoLabel;
    private javax.swing.JLabel buyComNameLabel;
    private javax.swing.JLabel buyComTaxNoLabel;
    private javax.swing.JLabel saleComInfoLabel;
    private javax.swing.JLabel saleComTaxNoLabel;
    // private javax.swing.JMenu jMenu1;
    // private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // private javax.swing.JMenuItem backupMenuBar;
    // private javax.swing.JMenuItem restoreMenuBar;
    // private javax.swing.JMenuItem historyInvoiceMenuBar;
    // private javax.swing.JMenuItem adjustModelMenuBar;

    // 发票打印
    private javax.swing.JToolBar jPrintViewToolBar;
    private javax.swing.JButton printButton;

    // 购方信息
    private javax.swing.JMenuItem buyComMenuBar;
    // 销方信息
    private javax.swing.JMenuItem saleComMenuBar;
    private javax.swing.JMenuItem goodsInfoMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private DatePicker drawDateField;
    private javax.swing.JTextField saleComBankNoField;
    private javax.swing.JTextField totalInWordField;
    private javax.swing.JTextField totalAmountField;
    private javax.swing.JTextField commentField;
    private javax.swing.JTextField payeeField;
    private javax.swing.JTextField drawerField;
    private javax.swing.JTextField industryClassField;
    private javax.swing.JTextField invoiceCodeField;
    private javax.swing.JTextField invoiceNoField;
    private JAutoComboBox buyComNameField;
    private javax.swing.JTextField buyComTaxNoField;
    private JAutoComboBox saleComNameField;
    private javax.swing.JTextField saleComTaxNoField;
    private javax.swing.JTextField saleComAddressField;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables

    private JDialog buyComDialog;
    private JDialog saleComDialog;
    private JDialog goodsInfoDialog;
    private JDialog printViewDialog;

    private BuyCompanyView buyComView;
    private SaleCompanyView saleComView;
    private GoodsInfoView goodsInfoView;
    private PrinterView printerView;
}
